---
stages:
- name: Build
  inputs:
  - service: ${REPO}
    type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    extension_id: ibm.devops.services.pipeline.container.builder
    target:
      region_id: ${REGION}
      organization: ${ORG}
      space: ${SPACE}
    IMAGE_NAME: us-micro-catalog-cloudnative-integration-fabio
    USE_CACHED_LAYERS: 'true'
    COMMAND: |-
      #!/bin/bash
      log_and_echo "Testy" 

- name: Deploy
  inputs:
  - type: job
    stage: Build
    job: Build
  triggers:
  - type: stage
  properties:
  - name: DESIRED_INSTANCES
    value: ${DESIRED_INSTANCES}
    type: text
  jobs:
  - name: Deploy
    type: deployer
    extension_id: ibm.devops.services.pipeline.docker.deploy.ice
    target:
      region_id: ${REGION}
      organization: ${ORG}
      space: ${SPACE}
    OPTIONAL_ARGS: -m "${MEMORY}"
    PORT: '8081'
    CONTAINER_NAME: us-micro-catalog-cloudnative-integration-fabio
    DEPLOY_TYPE: red_black
    COMMAND: |-
      #!/bin/sh

      set +e
     
      echo -e "${green}Execution complete${no_label}"
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
